"""added website to artists

Revision ID: 7e08a5f2189c
Revises: a3daece6af1d
Create Date: 2022-06-04 13:13:35.184379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e08a5f2189c'
down_revision = 'a3daece6af1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###
